
import java.util.ArrayList;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author JorgeLuis
 */
public class Frame_Principal extends javax.swing.JFrame {

    /**
     * Creates new form Frame_Principal
     */
    public Frame_Principal() {
        equipos = new ArrayList();
        agentes_libres = new ArrayList();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tf_nombreEquipo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        sp_copas = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        tf_estadio = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tf_presupuesto = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        jb_guardarEquipo = new javax.swing.JButton();
        jb_clearEquipo = new javax.swing.JButton();
        jb_salirCreacionEquipo = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jb_gestionEquipos = new javax.swing.JButton();
        jb_crearEquipo = new javax.swing.JButton();
        jb_crearJugador = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jb_arbolEquipos = new javax.swing.JButton();
        jb_fichajes = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel4.setText("Creación de Equipo");

        jLabel5.setText("Nombre");

        tf_nombreEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_nombreEquipoActionPerformed(evt);
            }
        });

        jLabel6.setText("No. de Copas");

        jLabel7.setText("Estadio");

        jLabel8.setText("Presupuesto");

        jLabel9.setText("$");

        jb_guardarEquipo.setText("Crear");
        jb_guardarEquipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_guardarEquipoMouseClicked(evt);
            }
        });

        jb_clearEquipo.setText("Clear");
        jb_clearEquipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_clearEquipoMouseClicked(evt);
            }
        });

        jb_salirCreacionEquipo.setText("Salir");
        jb_salirCreacionEquipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_salirCreacionEquipoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog1Layout.createSequentialGroup()
                        .addComponent(jb_guardarEquipo)
                        .addGap(18, 18, 18)
                        .addComponent(jb_clearEquipo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jb_salirCreacionEquipo)
                        .addGap(7, 7, 7))
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDialog1Layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(jLabel4))
                            .addGroup(jDialog1Layout.createSequentialGroup()
                                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel5))
                                .addGap(45, 45, 45)
                                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jDialog1Layout.createSequentialGroup()
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tf_presupuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(tf_nombreEquipo)
                                        .addComponent(sp_copas, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tf_estadio, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)))))
                        .addGap(18, 124, Short.MAX_VALUE))))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tf_nombreEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(sp_copas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tf_estadio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tf_presupuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_guardarEquipo)
                    .addComponent(jb_clearEquipo)
                    .addComponent(jb_salirCreacionEquipo))
                .addGap(26, 26, 26))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel1.setText("Liga Española Online 2018 Alpha");

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\JorgeLuis\\Desktop\\Lab-5Jorge_Garcia\\Lab#5_JorgeGarcia\\src\\Futbol.png")); // NOI18N

        jb_gestionEquipos.setText("Gestionar Equipos");

        jb_crearEquipo.setText("Crear Equipo");
        jb_crearEquipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_crearEquipoMouseClicked(evt);
            }
        });

        jb_crearJugador.setText("Crear Jugador");

        jButton4.setText("jButton4");

        jb_arbolEquipos.setText("Arbol de equipos");

        jb_fichajes.setText("Fichajes");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/default_user_icon.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jb_gestionEquipos))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jb_arbolEquipos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jb_fichajes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jb_crearJugador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_crearEquipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jb_gestionEquipos)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jb_crearEquipo)
                        .addGap(73, 73, 73)
                        .addComponent(jb_crearJugador))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addGap(73, 73, 73)
                        .addComponent(jb_arbolEquipos)))
                .addGap(39, 39, 39)
                .addComponent(jb_fichajes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_nombreEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_nombreEquipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_nombreEquipoActionPerformed

    private void jb_crearEquipoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_crearEquipoMouseClicked
        this.setVisible(false);
        this.jDialog1.setVisible(true);
        this.jDialog1.pack();
        this.jDialog1.setLocationRelativeTo(this);
    }//GEN-LAST:event_jb_crearEquipoMouseClicked

    private void jb_guardarEquipoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_guardarEquipoMouseClicked
        try {
            equipos.add(
                    new Equipo(this.tf_nombreEquipo.getText(),
                            Float.parseFloat(this.tf_presupuesto.getText()),
                            (int) this.sp_copas.getValue(),
                            this.tf_estadio.getText()
                    )
            );
            this.tf_nombreEquipo.setText("");
            this.tf_presupuesto.setText("");
            this.sp_copas.setValue(0);
            this.tf_estadio.setText("");
            JOptionPane.showMessageDialog(this.jDialog1, "¡El Equipo se creó exitosamente!");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this.jDialog1, "¡Ha ocurrido un error y no se agrego al jugador!");
        }
    }//GEN-LAST:event_jb_guardarEquipoMouseClicked

    private void jb_clearEquipoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_clearEquipoMouseClicked
        this.tf_nombreEquipo.setText("");
        this.tf_presupuesto.setText("");
        this.sp_copas.setValue(0);
        this.tf_estadio.setText("");
    }//GEN-LAST:event_jb_clearEquipoMouseClicked

    private void jb_salirCreacionEquipoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_salirCreacionEquipoMouseClicked
        this.jDialog1.dispose();
        this.setVisible(true);
        this.tf_nombreEquipo.setText("");
        this.tf_presupuesto.setText("");
        this.sp_copas.setValue(0);
        this.tf_estadio.setText("");
    }//GEN-LAST:event_jb_salirCreacionEquipoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton jb_arbolEquipos;
    private javax.swing.JButton jb_clearEquipo;
    private javax.swing.JButton jb_crearEquipo;
    private javax.swing.JButton jb_crearJugador;
    private javax.swing.JButton jb_fichajes;
    private javax.swing.JButton jb_gestionEquipos;
    private javax.swing.JButton jb_guardarEquipo;
    private javax.swing.JButton jb_salirCreacionEquipo;
    private javax.swing.JSpinner sp_copas;
    private javax.swing.JTextField tf_estadio;
    private javax.swing.JTextField tf_nombreEquipo;
    private javax.swing.JFormattedTextField tf_presupuesto;
    // End of variables declaration//GEN-END:variables
ArrayList<Equipo> equipos;
    ArrayList<Jugador> agentes_libres;
}
